# SPDX-FileCopyrightText: 2011- European Centre for Medium-Range Weather Forecasts (ECMWF)
# SPDX-License-Identifier: Apache-2.0

builds:
  - name: "conda-build"
    type: "conda"
    enabled: true

  - name: "hpc"
    type: "hpc"
    enabled: true
    config:
      modules:
        - python3

release:
  enabled: true
