set( ECBUILD_TRUST_FLAGS TRUE )
set( ECBUILD_C_FLAGS "-common" )
set( ECBUILD_C_FLAGS_DEBUG "-debugopts" )

set( ENABLE_OS_TESTS OFF CACHE BOOL "" )
set( ENABLE_LARGE_FILE_SUPPORT OFF CACHE BOOL "" )
