set( OVERRIDECOMPILERFLAGS_C_FLAGS "-g -fPIC" )
set( OVERRIDECOMPILERFLAGS_CXX_FLAGS "-g -fPIC" )
set( OVERRIDECOMPILERFLAGS_Fortran_FLAGS "-g -fortran_only_flag" )

set( OVERRIDECOMPILERFLAGS_C_FLAGS_DEBUG "-O0" )
set( OVERRIDECOMPILERFLAGS_CXX_FLAGS_DEBUG "-O0" )

set( OVERRIDECOMPILERFLAGS_C_FLAGS_BIT "-O2" )
set( OVERRIDECOMPILERFLAGS_CXX_FLAGS_BIT "-O2" )
