set( ECBUILD_MAJOR_VERSION "2" )
set( ECBUILD_MINOR_VERSION "3" )
set( ECBUILD_PATCH_VERSION "1" )

set( ECBUILD_VERSION_STR  "2.3.1" )

set( ECBUILD_MACRO_VERSION "${ECBUILD_MAJOR_VERSION}.${ECBUILD_MINOR_VERSION}" )
