# SPDX-FileCopyrightText: 2011- European Centre for Medium-Range Weather Forecasts (ECMWF)
# SPDX-License-Identifier: Apache-2.0

name: Check VERSION file

on:
  push:
    branches:
      - "release/**"
      - "hotfix/**"

jobs:
  check_version:
    uses: ecmwf/reusable-workflows/.github/workflows/check-release-version.yml@v2
