name: pre-commit

on:
  push:
    branches: [develop, master]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  pre-commit:
    runs-on: ubuntu-slim
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'
    steps:
      - uses: actions/checkout@v6
      - uses: ecmwf/ci-infrastructure/actions/pre-commit@main
